# Generated by Django 2.2.4 on 2019-08-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190825_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_social_network_id', to='api.SocialNetwork'),
        ),
        migrations.CreateModel(
            name='SocialNetworkAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network_accounts_social_network_id', to='api.SocialNetwork')),
            ],
        ),
    ]
