# Generated by Django 2.2.4 on 2019-10-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191019_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searched_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
