# Generated by Django 2.2.4 on 2019-10-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191019_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='sentiment_analysis_percentage',
            field=models.FloatField(default=0),
        ),
    ]
