# Generated by Django 2.2.4 on 2019-12-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_search_sentiment_analysis_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworkaccounts',
            name='quantity_by_request',
            field=models.IntegerField(default=0),
        ),
    ]
