# Generated by Django 3.0.4 on 2020-06-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_socialnetworkaccounts_quantity_by_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='word_root',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
