# Generated by Django 2.2.2 on 2019-06-30 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_language_id', to='frontend.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='WordRoots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_root', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('topics_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_roots_topics_id', to='frontend.Topics')),
            ],
        ),
        migrations.CreateModel(
            name='Searched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('polarity', models.CharField(choices=[('None', 'Neutral'), ('P', 'Positive'), ('N', 'Negative')], default='None', max_length=4)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('liked', models.IntegerField(default=0)),
                ('retweeted', models.IntegerField(default=0)),
                ('searched_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('polarity', models.CharField(choices=[('None', 'Neutral'), ('P', 'Positive'), ('N', 'Negative')], default='None', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionaries_language_id', to='frontend.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDictionaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('polarity', models.CharField(choices=[('None', 'Neutral'), ('P', 'Positive'), ('N', 'Negative')], default='None', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dictionaries_language_id', to='frontend.Languages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dictionaries_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
