# Generated by Django 2.2.2 on 2019-06-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customdictionaries',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='customdictionaries',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dictionaries',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='searched',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='wordroots',
            old_name='topics_id',
            new_name='topics',
        ),
    ]
