# Generated by Django 2.2.2 on 2019-06-30 17:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_auto_20190630_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('polarity', models.CharField(choices=[('None', 'Neutral'), ('P', 'Positive'), ('N', 'Negative')], default='None', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('polarity', models.CharField(choices=[('None', 'Neutral'), ('P', 'Positive'), ('N', 'Negative')], default='None', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='WordRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_root', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_root_topics_id', to='frontend.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionaries',
            name='language',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='language',
        ),
        migrations.RemoveField(
            model_name='wordroots',
            name='topics',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.DeleteModel(
            name='CustomDictionaries',
        ),
        migrations.DeleteModel(
            name='Dictionaries',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
        migrations.DeleteModel(
            name='WordRoots',
        ),
        migrations.AddField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_language_id', to='frontend.Language'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_language_id', to='frontend.Language'),
        ),
        migrations.AddField(
            model_name='customdictionary',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dictionary_language_id', to='frontend.Language'),
        ),
        migrations.AddField(
            model_name='customdictionary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dictionary_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
